import { PrismaClient } from "prisma/prisma-client";
const prisma = new PrismaClient();

async function seed() {
  await Promise.all(
    getPoesie().map((poesiaData) => {
      const data = poesiaData;
      return prisma.poesia.create({ data });
    })
  );
}

seed();

function getPoesie() {
  return [
    {
      name: "SACCO SCROTALE",
      content:
        "PORCODIO IL CAZZO DI FUORI. UN SACCO SCROTALE AL VENTO, I MIEI OCCHI VITREI, LA BAVA ALLA BOCCA, LA RUOTA NEL CASSETTO, LE MALATTIE MENTALI. IL CAZZO È DI FUORI PORCODIO.",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "SAN VALENTINO",
      content:
        "SAN VALENTINO, TI SIEDI CON TUO MARITO, RUMORE DI STRACCHINO, IL TUO CULO FARCITO DEL MIO FRUTTO PROIBITO. SAN VALENTINO, TUA MOGLIE È FELICE E NON SENTE IL TUO FIATO DI SEME, SIETE TUTTI FIGLI MIEI. COSI NELLA LAN VI SCOPO COL CAZZO MOSCIO PERCHÉ ERETTO NON LO MERITATE, SONO LA VERGA, SONO IL MARTELLO, VOI LE TERGA IN CUI RIMANERE INCASTRATO COME I CANI. PORCODIO ARRIVO.",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "SAPORITO!",
      content:
        "SAPORITO! IL CALLO DEL MIO ALLUCE TI FENDE LE LABBRA, IL CAZZO È A BATTUTA NELLE TUE BUDELLA E QUANDO TI STAPPERÒ SARÀ GRANDE FESTA. HURRÀ, SEMBRI UN GIRARROSTO, UNA PIGNATTA COLORATA. NELLA LANDA 5 VERGHE BASTONANO, NEI CESPUGLI PUZZA DI SODOMIA. IL GRUGNO DA CAVERNICOLO, LA RABBIA DEGLI F24, LE BOTTE ALLA MOGLIE, TI GUARDO AGONIZZANTE NEL PROLASSO E MI CI PERDO... SARÀ IL TEGRETOL RUBATO A MIO FRATELLO? MI ILLUMINO D'IMMENSO.",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "RIGATONE ALLA RICOTTA",
      content:
        "RIGATONE ALLA RICOTTA, SEI NOTO COSI, SEMPRE FARCITO. DAMMI ALMENO I BACINI SUL COLLO POROCDIO! JOAO PORCAMADONNA HO ANCORA LA FALOPA NEL CULO, MI PIZZICA IN RIUNIONE! SCUSATE HO SBAGLIATO CHAT...",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "QUINDICENNE",
      content:
        "L'ASTINENZA HA GONFIATO LA MAZZA, SE MI TOCCHI SBURRO COME UN QUINDICENNE. ALLORA CIUCCIAMI ANCORA, CON PASSIONE, LE PALLE NON MI FANNO PIÙ MALE, IL ROSSORE DELLE GUANCE È SVANITO, È TORNATO L'ANIMALE, LA MASCELLA SGANCIATA, LE RELAZIONI SOCIALI RIDOTTE ALL'OSSO, VOGLIA DI CULI GIOVANI. NELLA LANDA TI SCOPO DA DIETRO I MURETTI, ANCHE DA MORTO, PRENDO TUTTO. L'AMUCHINA LA USO PER SCIACQUARMI LA MINCHIA DAI VERMI COGLIONE. SONO TUA MADRE CHE SCURREGGIA IN BAGNO E TU CHE FAI FINTA DI NON SENTIRLA. SONO UN BACIO CHE SA DI CULO E BOCCHINI. SONO UNA CARTELLA DELL'AGENZIA DELL'ENTRATE CHE NON PUOI PERMETTERTI. SONO IL CAPELLO CHE CADE E TI FA VEDERE PELATO. MI RICONOSCI HO IL CAZZO DI FUORI, ARRIVO!",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "PECORINO!",
      content:
        "PECORINO! HAI FINITO IL RODAGGIO ALLE MASCELLE. TI HO COMMOSSO CON LO SBURRO E ORA HAI GLI OCCHI ROSSI. SONO IL TUO COLLIRIO PORCODIO. LA MAZZA SUL NASO TI DONA, TE LA LASCIO SULLA FACCIA COME CAPARRA. LA SBORRA COTTA GRATTATA E PIPPATA MI SEMBRA VERAMENTE TROPPO, E QUELLO È MIO GINOCCHIO PORCODIO!",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "CODA DI DRAGO",
      content:
        "LE PERE SULLA CAPPELLA, PIU CIOTTA, PIU CIOTTA. UNA SCATOLETTA DI TONNO, LA CLAVA DEL RETTORE, FINIAMO COME CHRIS BENOIT. TROMBOSI DELLA MINCHIA. LO SFORNACALLI DA CULO È PRONTO. ORA MANCANO I CULI, DOVE SONO I CULI PORCODIO? CORRI CON LA VERGA DEFORME E SCOVA I BUCHI. METTIAMO UN PLUG NEL CULO A FORMA DI CODA DI DRAGO E USTIONIAMO QUEI BUCHI PORCODIO",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/coda-di-drago.jpg",
    },
  ];
}
