import { PrismaClient } from "prisma/prisma-client";
const prisma = new PrismaClient();

async function seed() {
  await Promise.all(
    getPoesie().map((poesiaData) => {
      const data = poesiaData;
      return prisma.poesia.create({ data });
    })
  );
}

seed();

function getPoesie() {
  return [
    {
      name: "SACCO SCROTALE",
      content:
        "PORCODIO IL CAZZO DI FUORI. UN SACCO SCROTALE AL VENTO, I MIEI OCCHI VITREI, LA BAVA ALLA BOCCA, LA RUOTA NEL CASSETTO, LE MALATTIE MENTALI. IL CAZZO È DI FUORI PORCODIO.",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "SAN VALENTINO",
      content:
        "SAN VALENTINO, TI SIEDI CON TUO MARITO, RUMORE DI STRACCHINO, IL TUO CULO FARCITO DEL MIO FRUTTO PROIBITO. SAN VALENTINO, TUA MOGLIE È FELICE E NON SENTE IL TUO FIATO DI SEME, SIETE TUTTI FIGLI MIEI. COSI NELLA LAN VI SCOPO COL CAZZO MOSCIO PERCHÉ ERETTO NON LO MERITATE, SONO LA VERGA, SONO IL MARTELLO, VOI LE TERGA IN CUI RIMANERE INCASTRATO COME I CANI. PORCODIO ARRIVO.",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "SAPORITO!",
      content:
        "SAPORITO! IL CALLO DEL MIO ALLUCE TI FENDE LE LABBRA, IL CAZZO È A BATTUTA NELLE TUE BUDELLA E QUANDO TI STAPPERÒ SARÀ GRANDE FESTA. HURRÀ, SEMBRI UN GIRARROSTO, UNA PIGNATTA COLORATA. NELLA LANDA 5 VERGHE BASTONANO, NEI CESPUGLI PUZZA DI SODOMIA. IL GRUGNO DA CAVERNICOLO, LA RABBIA DEGLI F24, LE BOTTE ALLA MOGLIE, TI GUARDO AGONIZZANTE NEL PROLASSO E MI CI PERDO... SARÀ IL TEGRETOL RUBATO A MIO FRATELLO? MI ILLUMINO D'IMMENSO.",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "RIGATONE ALLA RICOTTA",
      content:
        "RIGATONE ALLA RICOTTA, SEI NOTO COSI, SEMPRE FARCITO. DAMMI ALMENO I BACINI SUL COLLO POROCDIO! JOAO PORCAMADONNA HO ANCORA LA FALOPA NEL CULO, MI PIZZICA IN RIUNIONE! SCUSATE HO SBAGLIATO CHAT...",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "QUINDICENNE",
      content:
        "L'ASTINENZA HA GONFIATO LA MAZZA, SE MI TOCCHI SBURRO COME UN QUINDICENNE. ALLORA CIUCCIAMI ANCORA, CON PASSIONE, LE PALLE NON MI FANNO PIÙ MALE, IL ROSSORE DELLE GUANCE È SVANITO, È TORNATO L'ANIMALE, LA MASCELLA SGANCIATA, LE RELAZIONI SOCIALI RIDOTTE ALL'OSSO, VOGLIA DI CULI GIOVANI. NELLA LANDA TI SCOPO DA DIETRO I MURETTI, ANCHE DA MORTO, PRENDO TUTTO. L'AMUCHINA LA USO PER SCIACQUARMI LA MINCHIA DAI VERMI COGLIONE. SONO TUA MADRE CHE SCURREGGIA IN BAGNO E TU CHE FAI FINTA DI NON SENTIRLA. SONO UN BACIO CHE SA DI CULO E BOCCHINI. SONO UNA CARTELLA DELL'AGENZIA DELL'ENTRATE CHE NON PUOI PERMETTERTI. SONO IL CAPELLO CHE CADE E TI FA VEDERE PELATO. MI RICONOSCI HO IL CAZZO DI FUORI, ARRIVO!",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "PECORINO!",
      content:
        "PECORINO! HAI FINITO IL RODAGGIO ALLE MASCELLE. TI HO COMMOSSO CON LO SBURRO E ORA HAI GLI OCCHI ROSSI. SONO IL TUO COLLIRIO PORCODIO. LA MAZZA SUL NASO TI DONA, TE LA LASCIO SULLA FACCIA COME CAPARRA. LA SBORRA COTTA GRATTATA E PIPPATA MI SEMBRA VERAMENTE TROPPO, E QUELLO È MIO GINOCCHIO PORCODIO!",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "NON C'E' LA LAN",
      content:
        "NON C'È LAN, MA NELL'ARIA ANCORA PROFUMO DI CULO. ABBONDO, TI AUTOCERTIFICO IL CAZZO SULLA FRONTE, TI SBORRO LE PARETI DI CASA, MA CON LA MASCHERINA. SONO IL FLAGELLO DEL DEMONIO. INFUSI CALDI DI PALLE PER IL MAL DI GOLA. STATE A CASA CHE VI TROMBO A DOMICILIO, VI SBORRO SULLA RIGA DEI CAPELLI E VI RUBO LO SHAMPOO.",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "L ALPHA E LA OMEGA",
      content:
        "STATE GIOCANDO BELLI TRANQUILLI SENZA POESIE EH. PORCODIO MI FATE VENIRE I GRICCIORI ALLA CAPPELLA. STA TORNANDO IL CAZZO E LA MAMMELLA, L ALPHA E LA OMEGA. L'UNTO DEL SIGNORE, IL SANGUINACCIO DIVINO. IL MITE AGNELLO REDENTORE. LA VERGA DEL SIGNORE CHE TOGLIE I PECCATI DAL MONDO COME UN ARATRO ZOLLA LA TERRA. AVETE CAPITO PORCODIO? ALLE 7 27 ESATTO PORCODIO. COSÌ, COL CAZZO TESO COME UNA COPPIETTA. PORCODIO",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "CAZZI SGONFI",
      content:
        "STAVATE LI COI CAZZI SGONFI A DIVERTIRVI. TORNA LA PREDA TORNA LA RUOTA LE INCAZZATURE TORNA LA LOCURA. TORNA TUTTA LA SPFFERENZA CHE VI FA ENTRARE IN RISONANZA CON LA VIA LATTEA. PORCODIO VORREI AVERE IL CAPS SUL CAPS",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "PROFESSOR DOTTORE",
      content:
        "OGGI TORNA IL CUORE IMMACOLATO DI MARIA! TORNA LO SPERMA PIU DOLCE DI MONTESACRO. IL SUONATORE DI BUCHI DI CULO . IL PROFFESSOR DOTTORE. PORCODIO !",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "DOVE NON BATTE MIA MADRE",
      content:
        "MA ORA È TUTTO CAMBIATO, SONO TORNATO SONO IL PISELLO BEATO LUCA, SONO IL VASCELLO DEL DEMONIO, SONO LA VERGA CHE PURGA DOVE NON BATTE MIA MADRE",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "5 PAGNOTTE",
      content:
        "OGGI VOGLIO CHE SI SENTA IL TANFO DEL CAZZO FINO AL LORO NEXUS PORCODIO. VOGLIO CHE CAPISCANO CHE ABBIAMO IL BIDE MA CHE NON LO USIAMO DI PROPOSITO! LI DOBBIAMO SCOPARE FIN DENTRO LA TERRA COI VERMI CHE GLI SI AFFACCIANO NEL BUCO DEL CULO. OGGI VOGLIO 5 PAGNOTTE DI CARNE INSANGUINATE. AVETE CAPITO POROCSIO?",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "MARTEDI'",
      content:
        "MARTEDÌ MI TROVATE IN TIRO COME IL CRISTO NEL GIARDINO DEI GETSEMANI MENTRE SI INCULAVA LA MADDALENA DIETRO GLI ULIVI E CI FACEVA CIUCCIARE GLI ALLUCI DA GIUDA",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "MARTEDI' SCORSO",
      content:
        "MARTEDÌ SCORSO CI HANNO SCOPATO LE FACCE. LE NOSTRE MANDIBOLE SLOGATE E SBURRATE GRIRANO VENDETTA. OGGI È IL GIORNO DEL PAPÀ, IL RITORNO DEL PATER FAMILIA. IL BOCCHINO D'ORO, OGGI LASCIAMO A CASA IL FRUMENTO E PRENDIAMO LA FALCE, ANDIAMO A MIETERE BUCHI DI CULO. COLTIVIAMO PROLASSI. OGGI SCOPIAMO SENZA IL CAZZO, SCOPIAMO CON LE VISCERE. PORCODIO PORCO",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "CAPODANNO",
      content:
        "LO SENTITE ? BUCO DI CULO E POLVERE DA SPARO, IL PROFUMO DELLA FELICITÀ. INIZIA LA STAGIONE DELLA CACCIA. UCCELLI ALLEPRATI, BUCHI FUMANTI, MASCELLE CHE SCROCCHIANO. RIZZOLLIAMO LA LANDA CON LE NOSTRE MINCHIE DEFORMI, I BOZZI DEL DESIDERIO INESPRESSO. TESTICOLI LIVIDI, UN CORDIALE BENVENUTO. IL FRAGORE CHE SQUARCIA IL CIELO, GLANDE CONTRO GLANDE, CULO CONTRO CULO. UN TRIPUDIO DI SPERMA ACIDO, VISCOSO, RANCOROSO. PORCODIO LA SEASON 2021 PRENDIAMO IL PLAT E LO SCOLO!",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "LA GANG BANG DEL BOSCO",
      content:
        "È TORNATA LA GANG BANG DEL BOSCO PORCODIO! PETTINATEVI IL PERINEO, RIMBOCCATEVI IL BUCO DEL CULO PERCHÉ OGGI SI VA PER VIGNE A FARE CAMPORELLE! BEVIAMO CORDIALE DAI PROLASSI DEI NOSTRI AVVERSARI. URRÀ URRÀ È TORNATO IL REDENTORE! URRÀ URRÀ È TORNATO IL MARMO DIVINO! URRÀ URRÀ VI PIPPIAMONNEL BUCO DEL CULO PER TUTTO L'ANNO MANNAGGIA AL CRISTO GUARDA",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "CLOPPITI CLOPPITI",
      content:
        "CLOPPITI CLOPPITI FA IL BOCCHINO. COSA BRILLA NELLA LANDA? È LO SBURRO DEL DIVINO! UGU UGU, AGA AGÀ, LE PALLE LI SOFFOCANO, LE BOLLE DAL NASO, LA SAFE WORD NON FUNZIONA PIÙ. SIAMO L'ERNIA DELLE TROPPE INGROPPATE, SIAMO LA NOTTE CHE CALA SULLE VOSTRE EREZIONI. SIAMO UN TALLONE NEL BUCO DEL CULO. UGU AGÀ, APRI LA BOCCA PORCODIO",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "LA RUOTA SILENTE",
      content:
        "LA RUOTA SILENTE VI DEVE VIBRARE NELL'ANO. SCRUTATE L'URETRA DEL COMPAGNO ALLA VOSTRA SINISTRA E CERCATE LA FORZA. DISTILLATE LA PREDA DI CHIAVARE NEL RIFT PER UNO SPERMA PIU DENSO E PIÙ COPIOSO. SIAMO LO SCROTO CHE ECLISSA IL SOLE! SIAMO IL GLANDE CHE ABBATE LE MURA DELLA CITTADELLA. PIPPIAMO PREDA E CORDIALE E FOTTIAMO CON IL DEMONIO NELLE PUPILLE PORCODIO. SCAPPATE, NASCONDETEVI NELLE GRINZE DELLE NOSTRE PALLE MENTRE NELL'ULTIMO AFFLATO RANTOLANTE VI SPARIAMO NEL CULO A SETTE ATMOSFERE CON LA MASCELLA SGANGHERATA. PORCADDIO PORCA.",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "LA TAVOLA DELLE CAPPELLE ROTONDE",
      content:
        "LA TAVOLA DELLE CAPPELLE ROTONDE SI È RIUNITA! TRASFORMIAMO LA LORO CENA IN UN FECALOMA. SPINGI E FARCISCI SPINGI E FARCISCI. VAPORE DI CULO CALDO, FUMANTE, CROCCANTE PICCANTE, IL TUO. ARRIVIAMO PORCODIO CON UN CARPIATO VI SCOPIAMO LE PROSPETTIVE DI BENESSERE. SIAMO IL LEVIATANO CRUDELE CHE SI NUTRE DEL CAOS, DELLA PAURA, DI QUEL PENE FLACCIDO E PENDENTE CHE HAI MENTRE FUGGI. SIAMO LA MASCELLA CHE SCROCCHIA QUANDO LA FIONDA È TROPPO PER LE CORONARIE. SIAMO IL TUO PORCODIDIO",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "CINQUE CAZZI BAVOSI",
      content:
        "CINQUE CAZZI BAVOSI NEL BUSH SWIPATO: QUELLO NODOSO, QUELLO LUCENTE, QUELLO CALLOSO, QUELLO CHE SIBILA, QUELLO CON GLI SPASMI. TUTTI ERETTI, PRONTI A INCULARE, SENZA FARE RUMORE. MI RAGLIA IL CULO PORCODIO! SIAMO LA SBORRA VELENOSA  DEL VARANO, SIAMO QUELLA BRUTTA MACCHIA  VISTA TROPPO TARDI. SIAMO IL RAGAZZONE AUTISTICO CHE ABUSA LA MAMMA PICCOLA E GRACILE. SIAMO LA DISGRAZIA COL CAZZO DI FERRO PORCODIOOO",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "CODA DI DRAGO",
      content:
        "LE PERE SULLA CAPPELLA, PIU CIOTTA, PIU CIOTTA. UNA SCATOLETTA DI TONNO, LA CLAVA DEL RETTORE, FINIAMO COME CHRIS BENOIT. TROMBOSI DELLA MINCHIA. LO SFORNACALLI DA CULO È PRONTO. ORA MANCANO I CULI, DOVE SONO I CULI PORCODIO? CORRI CON LA VERGA DEFORME E SCOVA I BUCHI. METTIAMO UN PLUG NEL CULO A FORMA DI CODA DI DRAGO E USTIONIAMO QUEI BUCHI PORCODIO",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/coda-di-drago.jpg",
    },
    {
      name: "LA SBORRA DEL CAPITANO",
      content:
        "LA SBORRA DEL CAPITANO È SEMPRE PIÙ DOLCE. I BOCCHINI LATERALI CON L'ABBRACCIO, LE PIPPE A COLTELLATA, LE PALLE CROCCANTI E TURGIDE. È TEMPO DI FRAGOLE CON LA PANNA. LO SBURRO DEL PAPÀ. IL BAMBINO DEL PISELLO, QUANDO SENTI CON L'URETRA UNO STRONZO IN FONDO AL CULO. IL CULO CALDO, IL MARE CALMO, LA PACE CATATONICA E BAVOSA DI UN TRANS A COPACABANA",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/sborra-del-capitano.jpg",
    },
    {
      name: "PASQUA",
      content:
        "PASQUA È PASSATA MA CONTINUIAMO A INFILARVI LE UOVA NEL CULO. MA PORCODIO ! BOCCHINO ALLA SALMONELLA, LA BRACE È PRONTA. MAMMA HO IL PISELLO PASTORIZZATO! STASERA VI MANTECHIAMO IL BUCO DEL CULO.",
      author: "GIANCAPS",
      imgUrl: "https://f004.backblazeb2.com/file/poesie-dalla-landa/pasqua.jpg",
    },
    {
      name: "DL RISTORI",
      content:
        "SVEGLIA SVEGLIA! TI PRENDO A SCHIAFFI E TI SPUTO NEL CULO. È ARRIVATO IL PISELLO DEL GENITORE. L AUGELLO MALATO, LA CRESTA DI GALLO CHE NON TI DÀ TREGUA. SONO IL DL RISTORI, LA RETRIBUZIONE VISCOSA. ANCHE COL CAZZO MOSCIO TI SCOPO LE GIORNATE. URCA URCA CHE CAPPELLA, URCA URCA SONO L'ARNESE DI PAPÀ!",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/dl-ristori.jpg",
    },
    {
      name: "AL SOLE COME UNA LUCERTOLA",
      content:
        "A 50 ANNI PENSI CHE METTENDOTI AL SOLE COME UNA LUCERTOLA QUALCUNO VORRÀ FOTTERTI IL CULO PIÙ FORTE, CHE QUALCUNO RIESCA A TOLLERARE QUELLA NOTA FASTIDIOSA CHE RAGGIUNGI QUANDO RIMPROVERI TUO FIGLIO PERCHÉ NON SI LAVA LE MANI PRIMA DI TOCCARE IL PANE DI TUTTI E HA SEMPRE LE DITA IMPIASTRICCIATE DI CAZZO. INVECE PORCODIO INDOVINA UN PO'? LA TUA PELLE RUVIDA, BEN COTTA, RICORDA PROPRIO QUELLA DELLA LUCERTOLA. NESSUNO SI SCOPA I RETTILI. NESSUNO CHIEDE L'OSTRICA SENZA L'ACQUA PORCODIO. DOMENICA SCORSA SIAMO STATI COSÌ. SUL LETTINO A SPERARE DI SCOPARE PRENDENDO IL SOLE. CI SIAMO BECCATI SOLO UNA NEOPLASIA DELLA PELLE CHE COVA METASTASI TRA LE GRINZE, ANCOR PIÙ GRINZOSE, DEL NOSTRO BUCO DEL CULO. NON ABBIAMO PIÙ IL CAZZO! DA OGGI SIAMO VONGOLE! VONGOLE SENZA SUCCO, VONGOLE PIENE DI SABBIA DI QUELLE CHE TI MANDANO STORTO LO SPAGHETTO. MERDE",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/lucertola.jpg",
    },
    {
      name: "PAPA'",
      content:
        "OH NO PAPÀ, IL PISELLO NO PAPÀ? CHE BARBA PAPÀ! C'È MAMMA PAPÀ. OH NO OH NO! NON VOGLIO FARE UGU AGA. OH NO PAPÀ. È IL CAZZO PAPÀ. CHE MALE CHE FA. CHE BENE CHE DÀ. L'UCCELLO PAPÀ. È DURO PAPÀ. COL SUGO PAPÀ? A BATTUTA NEL CULO PAPÀ.  LA VERGA DI ALLAH, IN CULO FA CICK CIAK.",
      author: "GIANCAPS",
      imgUrl: "https://f004.backblazeb2.com/file/poesie-dalla-landa/papa.jpg",
    },
    {
      name: "TOCCARE",
      content:
        "NON TOCCARE LA MIA MERDA PORCODIO! STA ZITTO PORCODIO PORCO! BOCCHINO ASCIUTTO! CAPRA ORFANA! PORCODIO DEVI SEMPRE STARE MUTO SEI UN PUGNO NEL CULO. TI PIACE COSI? TI PIACE COL FRUSTINO SU PER IL CULO? ARRIVA COSI OGGI, TE LO BECCHI COSI COME VIENE, MOSCIO? E MOSCIO SIA. BARZOTTO? BARZOTTO SIA. OGGI SONO TIZIANO RONALDO, OGGI SONO BRODO MOMOA. NON TOCCARE LE CARTE PORCODIO. NON MI GUARDARE MENTRE MI SCOPO IL CANE! AGSJRKFNF TI GRUGNISCO NEL CULO PIU FORTE DELLA PAURA DI MORIRE",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/toccare.jpg",
    },
    {
      name: "CULO SPORCO ACQUA CALDA E BID3",
      content:
        "ANCHIMO ANCHIMO IL MIO CAZZO FA TIK TOK È UN UCCELLO O UN NARGHILÈ? TU CI FUMI ED È BID3! O MIO DIO O DIO MIO QUESTO UCCELLO MI DÀ BRIO. IO TI FOTTO AD OCCHI CHIUSI COLLA MINCHIA NEI RIFIUTI. TI SCAVO NEL CULO TI SCAVO DA SOLO. SONO IL RE DELLO SCOLO TE LO PASSO, TE LO DONO. PORCODIO CULO SPORCO ACQUA CALDA E BID3",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "ANGURIO",
      content:
        "ANGURIO! ANGURIO! HA L'UCCELLO DI UN COCOMERO, LA CAPPELLA A POIS. GLI PIACE FARE GLANDE GLANDE NELLA TERRA DEI PAPÀ! È PREDILETTO, INTORNO ALLA MINCHIA HA IL MERLETTO, È IL FRUTTO SUCCOSO DEL CULO VIZIOSO! OGGI È LUCIDO E SCAPPELLATO, BELLO ERTO E INGRIFATO! ANGURIO ANGURIO, NEL CULO TI SBURIO!",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/angurio.jpg",
    },
    {
      name: "BOCCA DI RANA",
      content:
        "UNA BELLA STROZZATA DI PALLE, BOCCA DI RANA BOCCA DI RANA, AFFONDA SENZA GAG. NON C'È UGU, NON C'È AGA. LA BOCCA PIENA DI PALLE DEL PAPÀ. NON UNA LACRIMA. SOLO PIZELO. SOLO PIZELO PAPÀ. I PUGNI SUI RENI, LA CAPPELLA NELLA GUANCIA. CASTORINO PAPÀ. ECCOLO QUA. TI STAPPO COME UN RONCO PORGODIO",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/bocca-di-rana.jpg",
    },
    {
      name: "REGALO",
      content:
        "IL GENETLIACO DI UNA ANCELLA CAPPELLA SI CELEBRA RIDENTI COI CANDELABRI NEL CULO. SOFFIA ANCELLA SOFFIA È UNA TORTA DI FALLIMENTI E RANCORE, LA TUA PREFERITA! SONO IL PACCO REGALO DEFORME E BOZZUTO CHE SOGNI DI NOTTE MENTRE LEI DORME. SONO IL FRUTTO PROIBITO CHE TI FA EBRO E SATOLLO. OGGI ABBUFFATI DEL VAPORE CALDO DI UN CULO LAIDO, DELLA MUFFA DI UN SOTTOPALLA ASCIUGATO MALE. EVVIVA GESÙ, PERCHÉ BEATI SONO GLI INVITATI ALLE NOZZE DELL'AGNELLO. L'AGNELLO CAPPELLA, L'AGNELLO PAPÀ, OH NO, OH NO, L'AGNELLO FA BAAA, L'AGNELLO FA BAAA, COL DITO FA BA!",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/bocca-di-rana.jpg",
    },
    {
      name: "MANICOTTO",
      content:
        "MANICOTTO MANICOTTO, DENTRO AL CULO BELLO CIOTTO. È UN LAMPREDOTTO? NO, È UN BEL DICIOTTO. TI SCOPA COL MOSCIONE, IL RUSSO NEL FURGONE, TI MENA E DICE ZITTO, LUI CHE È SAGGIO NEL DIRITTO. È L'AVVOCATO DELLE VERGHE SGHEMBE, IL VASCELLO DELLE TERGHE TAMBURELLATE PORCA MADONNA URRÀ URRÀ, È ARRIVATO TI METTE IL CAVIALE NEL CULO E TE LO SPINGE NELLO STOMACO PPRCODIO PORCO",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/manicotto.jpg",
    },
    {
      name: "CREMINO",
      content:
        "OPS È UN CREMINO, OH NO TROPPO DENTRO A QUEL BUDINO. COSA BRILLA IN QUEL BOCCHINO? SARÀ IL PASSERO DIVINO? È L'AUGELLO DEL BAMBINO, CHE FA PIPÌ, FA PIPÌ NEL TUO CULO FA PLIN PLIN, TUTTO IL GIORNO TI PERCUOTE, SEMBRA UN GLANDE MA HA LE RUOTE. DENTRO AL TUO DOLCE BUDINO, TROPPO A FONDO, C'È UN CREMINO.",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/cremino.jpg",
    },
    {
      name: "RABBIA",
      content:
        "BOCCHE DEFORMI IMPASTATE DI BAVA SCHIUMOSA GOLE DOLENTI E CULI URTICATI LA FULGIDA DOMENICA DEL SIGNORE BELANTE È DI FRONTE A VOI ROMPETE I VOSTRI SALVADANAI PER LO SCIALACQUO DI OTTOBRE SEDICENTI SEDICENNI CHUBBY TRAVESTITE DA SAYLOR MOON IN REALTÀ BUZZICONI BRUFOLOSI SENZA AMICI",
      author: "BJz",
      imgUrl: "https://f004.backblazeb2.com/file/poesie-dalla-landa/rabbia.jpg",
    },
    {
      name: "QUE BELLO",
      content:
        "UGGIOSO L’AUGELLO, L’ETTERNO DOLORE NEL RETTO RANDELLO. QUE BELLO, QUE BELLO, È IL GIORNO NOVELLO, CI METTO IL PIZELLO, CI METTO IL TACCHINO FARCITO TRA IL SACRO E IL FACETO. SOLLAZZO MAI SAZIO QUEL CULO, MARRAZZO! BLEM BLEM, TUM TUM, CIA CIA, RUMORI DI CULO DALL’AL DI LA. NODI DI SPERMA, GRUMI DI DESIO, TI SGOTTO NELL’ANTRO PER L’AMORE DI DIO. SBORRO SENZA GRUGNITO, SAPPILO…",
      author: "BJz",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/que-bello.jpg",
    },
    {
      name: "LE BOCCHE DEFORMI",
      content:
        "LE BOCCHE DEFORMI \n OH SIGNORE OH PADRONE \n SCOPIAMO ANCHE QUELLE STASERA SE SERVE \n SE PIACE SIGNORE \n LE BOCCHE TUO PADRE \n CHE MERDA DIO CANE",
      author: "BJz",
      imgUrl: "",
    },
    {
      name: "BOCCHE",
      content:
        "BOCCHE BOCCHE BOCCHE \n BOCCHE FARCITE \n BOCCHE RIPIENE \n STRABORDANTI SBAVATE SCHIUMATE MERDE SIETE VOI LE BOCCHE CHE GIOCANO SVOGLIATE \n LE BOCCHE CHE ROAMANO \n BOCCHE SENZA VISION \n",
      author: "BJz",
      imgUrl: "",
    },
    {
      name: "NON MANGIA PESCE",
      content:
        "NON LO DI MERDA NON MANGIA PESCE E DI MERDA DI SOLDI PAPÀ! RIPARTIAMO DAL TANFO STAPPATO DI CULO PAPÀ! \n SIAMO L’ULTIMO AFFLATO DI BOCCA SBORRATA BABBÀ! \n RINASCIAMO DI ZOLFO E DI FIATO DI CULO DI NASO \n PIPPATO DI CANTO STROZZATO DI CAZZO NEL CULO BABBÀ! \n SIAMO IL CANTO STRAZIATO DEL CULO STRACCIATO DI MILLE PUTTANE BAMBINE IN GABBIA SCOPATE BABÀ!\n NON VOGLIO PULIRE PIÙ CULI NEL RIFT, NON VOGLIO LE FECI SBRATTATE SUL VOLTO DA CAZZI SGHEMBI PORCODIO! \n VOGLIO CACARE SULLE TESTE A SINCRO COME GLI STORMI DI STORNI SULLA FACCIA DEL SOGNATORE, VOGLIO 5CULI PERFETTI PER UN UNICO DILDO DI LEGNO DI QUERCIA SALDATO DA MILLE PROLASSI GISBORRO GISBORRO GISBORRO BABÀ !!!",
      author: "GIANCAPS",
      imgUrl: "https://f004.backblazeb2.com/file/poesie-dalla-landa/pesce.jpg",
    },
    {
      name: "PENA",
      content:
        "DEI CAZZI PENOSI CHE VAGANO AL BUIO \n SBRATTI INCAPACI MONGAPPATI MIOPI \n ROAMIAMO SENZA SENSO E SENZA META \n A CHASARE COME LA MERDA CHE MANGIATE E \n DATE DA MANGIARE. \n CRANI VUOTI DI BAMBINI DEFORMI RIEMPITI SOLO DAL SEME DEI MINORATI CHE RIUSCIAMO A FEEDDARE",
      author: "BJz",
      imgUrl: "",
    },
    {
      name: "SOGNO ZINCATO",
      content:
        "ECCOLO LÌ ECCOLO QUA MI SCOPA IL CRAGNO QUEL BUCO DORATO, DI SBURRO COLATO LO SOGNO ZINCATO. MI FRIGGE IL CRAGNO L IDEA DI SBURRARLO COLATO PORCODIO PORCODIO SBURRATO. IL BUCO IL BUGO IL BUGO BABBÀ, LO VOGLIO LO VOGLIO BABBÀ! GISBORRO E GISGOTTO BABBÀ! MI COMPRI QUEL CULO BABBÀ? LO SBORRO BABBÀ! AIUTO AIUTO IL MENESTRELLO DELLA MIA CAPPELLA UMIDA NON MOLLA LA PRESA LE GOCCE CALDE DI CONDENSA DI CAZZO BABBA! \n STO LOCO STO LESO SONO L IRREPRENSIBILE VOGLIA BAVOSA CHE TI COLA SULLA SCHIENA MENTRE ME LO MENO MANNAGGIA A DIO MANNAGGIA PORCODIO! È UN NODULO AL CRAGNO DI DESIO, NO BASTA TI STAPPO COME UN RONCÒ MANNAGGIA AL CRISTO LE PERE DI TESTOSTERONE LA DEVO SMETTERE STASERA SOLO CARCASSE!",
      author: "GIANCAPS",
      imgUrl: "",
    },
    {
      name: "CODA DI DRAGO",
      content:
        "LE PERE SULLA CAPPELLA, PIU CIOTTA, PIU CIOTTA. UNA SCATOLETTA DI TONNO, LA CLAVA DEL RETTORE, FINIAMO COME CHRIS BENOIT. TROMBOSI DELLA MINCHIA. LO SFORNACALLI DA CULO È PRONTO. ORA MANCANO I CULI, DOVE SONO I CULI PORCODIO? CORRI CON LA VERGA DEFORME E SCOVA I BUCHI. METTIAMO UN PLUG NEL CULO A FORMA DI CODA DI DRAGO E USTIONIAMO QUEI BUCHI PORCODIO",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/coda-di-drago.jpg",
    },
    {
      name: "L'UCCELLO MALATO",
      content:
        "M’ATTIZZA LA SBARRA LA MUCCA LA LOLA FA MU DALLA BOCCA INCULATA LA RUOTA DI SBORRA STAPPATA E FRESCA SBURRATA BABBÀ! TUTTO D UN FIATO BELLO IMPIASTRICCIATO È LUCCELLO MALATO MALATO MALATO SALATO DI BAVA DI TROIA DI CULO DI TRANS DELL AMICO PIPPATO BABBÀ! È COSÌ È COSÀ È LA TROIA PIÙ LAIDA LA VERGOGNA DI CASA LA CAGNA VACCINA LA SBURRA BUCCHINA ORA BASTA BABBÀ MI SPARO SUL CAZZO NEL RIFT FACCIO PENTA SCOPPIATO SCOPPIATO PORCODIO HAI CAPITO PORCODIO BABBÀ?",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/uccello-malato.jpg",
    },
    {
      name: "MERLINO",
      content:
        "IL CAZZO RINCHIUSO NELLA TOPPA CHE UN TEMPO SBORRATA STA TUTTA INCROSTATA CHE BARBA CHE NOIA DI SBURRO STANTIO SENZA CULO SCOPATO TRISTEZZA SAUDAGI A PECORA PIACI FARCITA A STANTUFFI DI PUGNI NEL CULO CHE BARBA BABBÀ! \n MERLINO MERLINO È UN CAZZO ZECCHINO LO GONFIO LO ALLARGO QUEL CULO MAI SALDO MAI SALVO MA SALGO NEL CULO TI CRESCO PIAN PIANO DI SBURRO VISCOSO. GI STROZZO GISBORRO GISBOCCO SONO FIENO DI TE SONO FIENO DEL FIATO DEL VECCHIO GIÀ MORTO SPIRATO SU UN CULO CACATO A NATALE PULITO DA BABBO PAPÀ",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/merlino.jpg",
    },
    {
      name: "MASSAGGIO PROSTATICO NEGATO",
      content:
        "SULL’ORLO SULLORLO NELL ORTO C’È IL CRISTO CHE COGLIE LA RABBIA NEI CAMPI IL BABBINO GESÙ. HA TUTTO LUGGELLO IRRITATO SBORRATO INCAZZATO DI CULO STAPPATO DI COVID STANATO IL TAMPONE DI CARNE DA SOLO NELLA GROTTA GESÙ. \n FESTANTE LA MINCHIA ROTANTE LA BAMBA PIPPATA SUL GLANDE PIÙ GRANDE, DI FREGNE MAI SAZIE DI SOLDI E DI MERCE SI GONFIA LE TASCHE E LE PALLE E TI SCOPA SENZA PENSARE, SENZA BADARE, SENZA PRETENDERE AMORE. È IL RIGURGITO CHE SA DI CULO NON DIGERITO, IL MASSAGGIO PROSTATICO NEGATO DI CHI VUOLE SBORRARE DI PIÙ MA NON PUÒ SI NON PUÒ LUI NON PUÒ VUOLE DARE TUTTA LA SBORRA FINCHÉ NON NE HA PIÙ MA NON PUÒ IL BAMBINO DIVINO DEL FIGLIO GESÙ",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/massaggio-prostatico.jpg",
    },
    {
      name: "PASTORE",
      content:
        "SONO IL PASTORE IL MUNTO DALLE SIGNORA LA SISA DEL DIVINO IL CAZZO PIÙ BELLINO. È LA MINCHIA PARLANTE LUCENTE BELANTE GESÙ IL CAZZO PIÙ LINDO PIÙ PINDO PIÙ LAIDO BUBÙ! TI PIPPO IL MIO SBURRO COME LA COLLA I BAMBINI AFRICANI LAGGIÙ . LA LAIDA CHE PUZZA DEL CULO PIÙ BUIO PIÙ SCURO PIÙ NERO SEI TU ! MI BELA LUCCELLO MI BELA LUCCELLO QUE BELLO QUE BELLO QUE LINDO QUE RICO SON TUTTO CIUCCIATO E DIPINTO DI TU! SBORRO PRIMA PORCODIO MERDA",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/pastore.jpg",
    },
    {
      name: "CAPRETTO",
      content:
        "SONO IL PASTORE IL MUNTO DALLE SIGNORA LA SISA DEL DIVINO IL CAZZO PIÙ BELLINO. È LA MINCHIA PARLANTE LUCENTE BELANTE GESÙ IL CAZZO PIÙ LINDO PIÙ PINDO PIÙ LAIDO BUBÙ! TI PIPPO IL MIO SBURRO COME LA COLLA I BAMBINI AFRICANI LAGGIÙ . LA LAIDA CHE PUZZA DEL CULO PIÙ BUIO PIÙ SCURO PIÙ NERO SEI TU ! MI BELA LUCCELLO MI BELA LUCCELLO QUE BELLO QUE BELLO QUE LINDO QUE RICO SON TUTTO CIUCCIATO E DIPINTO DI TU! SBORRO PRIMA PORCODIO MERDA",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/capretto.jpg",
    },
    {
      name: "CAZZO E MAMMELLA",
      content:
        "LA FACCIA SBORRATA INCROSTATA INCULATA NON PIACE A BABBÀ! OH NO, NO NO NO NON LA VUOLE BABBÀ! LA VUOLE DI LINDO IMBIANCATA DI BAMBA INNEVATA DI FREGNA DI CULO TAMBURO DEL CAZZO PIÙ TURGIDO ERETTO BUBÙ! UN’ORCHESTRA DI COITI STRILLANTI DI CAZZI ARREMBATI LA LANDA LAGGIÙ! AGU AGU TI RAGLIA LA BAVA MASCELLA INCASTRATA INCAZZATA DEL PORCO DEL DIO. LA NOTTE PIÙ BUIA È CALATA È GIUNTA L ADUNATA DEI PIÙ BIECHI SELVAGGI BRIGANTI I CAZZI STRILLANTI LE FIAMME DAL CULO TI SALDANO L’ERNIA SEI LA CORATELLA DELLA MIA CAPPELLA PIÙ LERCA PIÙ BIECA PIÙ CIECA PIÙ CAZZO E MAMMELLA PIÙ CAZZO E MAMMELLA PIÙ CAZZO E MAMMELLA QUE BELLA QUE BELLA LA RABBIA DEI CAZZI LA LANDA CHIAMÒ!",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/cazzo-mammella.jpg",
    },
    {
      name: "CAPPUCCINO",
      content:
        "LA FACCIA SBORRATA INCROSTATA INCULATA NON PIACE A BABBÀ! OH NO, NO NO NO NON LA VUOLE BABBÀ! LA VUOLE DI LINDO IMBIANCATA DI BAMBA INNEVATA DI FREGNA DI CULO TAMBURO DEL CAZZO PIÙ TURGIDO ERETTO BUBÙ! UN’ORCHESTRA DI COITI STRILLANTI DI CAZZI ARREMBATI LA LANDA LAGGIÙ! AGU AGU TI RAGLIA LA BAVA MASCELLA INCASTRATA INCAZZATA DEL PORCO DEL DIO. LA NOTTE PIÙ BUIA È CALATA È GIUNTA L ADUNATA DEI PIÙ BIECHI SELVAGGI BRIGANTI I CAZZI STRILLANTI LE FIAMME DAL CULO TI SALDANO L’ERNIA SEI LA CORATELLA DELLA MIA CAPPELLA PIÙ LERCA PIÙ BIECA PIÙ CIECA PIÙ CAZZO E MAMMELLA PIÙ CAZZO E MAMMELLA PIÙ CAZZO E MAMMELLA QUE BELLA QUE BELLA LA RABBIA DEI CAZZI LA LANDA CHIAMÒ!",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/cappuccino.jpg",
    },
    {
      name: "VENDEMMIA",
      content:
        "MAMMELLO MAMMELLO L’EFFIGE È L UGELLO SALTELLO LO SBERLO NEL CULO LO SMELLO LA GRANDE CAPPELLA GHE BELLO STASERA SON TUTTO PIZELLO PER TU! UN UNICO CULO SCOPATO FLAMBATO BELATO FARCIATO DEL GRANDE CREATO IL TEAM È TORNATO COL CAZZO E IL CULETTO INFIAMMATO MA TUTTO SOMMATO SBORRANDO DI PIÙ! \n VENDEMMIA SU VITI DI MINCHIE DEFORMI BOZZUTE DI NETTARE ACIDO PUZZA DI CAZZO DI SANGUE DI CULO GU GU GUGUGUGUGUGUGU SONO TUTTO MASCELLA TI SBANO PIZELLA SON GLANDE E MAMMELLA DEL PORCOGEZU",
      author: "GIANCAPS",
      imgUrl:
        "https://f004.backblazeb2.com/file/poesie-dalla-landa/vendemmia.jpg",
    },
  ];
}
